import logging
import requests
import json
import os

# --- Constants ---
TEAMS_WEBHOOK_URL = os.environ.get("TEAMS_WEBHOOK_URL")
CLIENT_ID= os.environ.get("CLIENT_ID")
CLIENT_SECRET= os.environ.get("CLIENT_SECRET")
# --- Mock Function ---

def send_teams_notification(message: str):
    """Mocks sending a notification to a Microsoft Teams webhook."""
    logging.info("Sending notification to Microsoft Teams...")
    payload = {
        "@type": "MessageCard",
        "@context": "http://schema.org/extensions",
        "themeColor": "0076D7",
        "summary": "New Suggestion from LLaMA2",
        "sections": [{
            "activityTitle": "New Suggestion from LLaMA2",
            "activitySubtitle": "Generated by the Agent",
            "facts": [{
                "name": "Suggestion",
                "value": message
            }],
            "markdown": True
        }]
    }

    logging.debug(f"Teams payload: {json.dumps(payload, indent=2)}")

    # In a real scenario, you would make a request like this:
    # response = requests.post(TEAMS_WEBHOOK_URL, json=payload)
    # logging.info(f"Teams notification sent with status code: {response.status_code}")
    
    # For this example, we'll just print the payload.
    print("Simulating sending notification to Teams.")
    logging.info("Mock Teams notification sent.")